POST http://localhost:4001/api/users
Content-Type: application/json

{
    "email": "user10@example.com",
    "password": "123456K*",
    "name": "Trial",
    "gender":"male",
    "birthDate":"2000-01-01",
    "country":"Spain"
}